# Generated by Django 5.0.1 on 2024-01-29 08:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("learning_logs", "0002_entry"),
    ]

    operations = [
        migrations.AddField(
            model_name="entry",
            name="hashtag",
            field=models.CharField(default="#main", max_length=100),
        ),
    ]
